# Generated by Django 2.2.3 on 2019-07-30 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheWall', '0003_auto_20190730_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='person',
        ),
    ]
