# Generated by Django 2.2.3 on 2019-07-30 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheWall', '0005_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
